const RouteName = {
    BOTTOM_TAB_NAVIGATOR: "BottomTabNavigator",
    SPLSH_SCREEN: "SplashScreen",
    ONBOARDING_SCREEN: "OnboardingScreen",
    SIGNIN_SCREEN: "SignInScreen",
    SIGNUP_SCREEN: "SignUpScreen",
    OTP_VERYFY_SCREEN: "OtpVerifyScreen",
    FORGOT_PASSWORD_SCREEN: "ForgotPasswordScreen",
    HOME_SCREEN:"HomeScreen",
    CATEGORY_SCREEN:"CategoryScreen",
    MY_PROFILE_SCREEN:"MyProfileScreen",
    WISHLIST_SCREEN:"WishlistScreen",
    MY_CART_SCREEN:"MyCartScreen",
    LANGUAGE_SCREEN:"LanguageScreen",
    LOCATION_SCREEN:"LocationScreen",
    EDIT_PROFILE_SCREEN:"EditProfileScreen",
    SAVE_ADDRESS_SCREEN:"SaveAddressScreen",
    ADD_ADDRESS_SCREEN:"AddAddressScreen",
    ABOUT_SCREEN:"AboutScreen",
    TERMS_CONDITION_SCREEN:"TermsConditionScreen",
    PRIVACY_POLICY_SCREEN:"PrivacyPolicyScreen",
    CHANGE_PASSWORD_SCREEN:"ChangePasswordScreen",
    SUPPORT_SCREEN:"SupportScreen",
    NOTIFICATION_SCREEN:"NotificationScreen",
    COUPON_SCREEN:"CouponScreen",
    MY_WALLET_SCREEN:"MyWalletScreen",
    ADD_MONEY_SCREEN:"AddMoneyScreen",
    SETTING_SCREEN:"SettingScreen",
    NOTIFICATION_SETTING_SCREEN:"NotificationSettingScreen",
    TRANSACTION_SCREEN:"TransactionScreen",
    PAYMENT_METHOD_SCREEN:"PaymentMethodScreen",
    CATEGORY_PRODUCT_SCREEN:"CategoryProductScreen",
    PRODUCT_DETAILS_SCREEN:"ProductDetailsScreen",
    SEARCH_BAR_SCREEN:"SearchBarScreen",
    SEARCH_SCREEN:"SearchScreen",
    CHECKOUT_SCREEN:"CheckoutScreen",
    ORDER_SUCCESS_SCREEN:"OrderSuccessScreen",
    MY_ORDER_SCREEN:"MyOrderScreen",
    TRACK_ORDER_SCREEN:"TrackOrderScreen",
    CHAT_SCREEN:"ChatScreen",
    INVOICE_SCREEN:"InvoiceScreen",
    REVIEW_SCREEN:"ReviewScreen",
    APP_REVIEW_SCREEN:"AppReviewScreen",
    ALL_SCREEN:"AllScreen",
}
export default RouteName;