const Strings = {
  appname: "GreenMart",
  label: {
      "Home": "Home",
      "MyProfile": "My Profile",
      "SelectLanguage":"Choose Language",
      "TermsCondition":"Terms & Condition",
      "PrivacyPolicy":"Privacy Center",
      "Back":"Back",
      "Search": "Search",
      "Logout": "Logout",
      "EditProfile": "Edit Profile",
      "ChangePassword": "Reset Password",
      "SaveAddress": "Save Address",
      "AddAddress": "Add Address",
      "About": "About",
      "CustomerSupport": "24x7 Customer Support",
      "MyNotification": "My Notification",
      "MyCart": "My Cart",
      "MyWishlist": "My Wishlist",
      "Coupon": "My Coupon",
      "MyWallet": "My Wallet",
      "AddMoney": "Add Money",
      "Settings": "Settings",
      "Notification": "Notification",
      "Transaction": "Transaction",
      "PaymentMethod": "Bank & UPI Details",
      "Category": "All Categories",
      "Checkout": "Checkout",
      "MyOrder": "My Order",
      "TrackOrder": "Track Order",
      "Chat": "Chat Support",
      "Invoice": "Invoice",
      "Review": "Rate & Review",
      "AllScreen": "All Screen",
  }
}

export default Strings;