

export const darkColors = {
  primary_color: '#008000',
  tea_green_color: '#cce6cc',
  tea_green_light_color: '#d6f3d6ff',
  secondary_color: '#FE9801',
  secondary_light_color: '#ffcd42ff',
  secondary_light1_color: '#fff2cdff',
  black: '#000000',
  white: '#ffffff',
  white_transparent: '#ffffff7e',
  pine_green_color: '#004D00',
  mint_green_color: '#66BB66',
  earthy_brown_color: '#8B4513',
  gainsboro: "#ebe9e8",
  mint_white: "#141414ff",
  mint_dark_white: "#090a0aff",
  forest_green: "#6baf6b",
  eton_green: "#94cf94",
  bright_gray: "#474747",
  cultured: "#1a1a1a",
  red_light_color: "#fad7d9",
  background_color: '#0d0d0dff',
  background_white_color: '#0d0d0dff',
  background_box_color: '#1e211eff',
  light_box: '#f9faf9ff',
  bright_gray_dark: '#d9d9d9',
  bright_gray01: '#212121ff',
  gray: '#8b8b8b',
  light_gray: "#393939",
  layer_black: "#00000075",
  light_primary: '#fdf5f6',
  background: '#ffffff',
  light_black: '#bdbdbd',
  text_color_white: '#ffffff',
  light_gray_01: '#1a1a1aff',
  transparent: 'transparent',
  grey: 'grey',
  red_color: "#e72f07",
  fix_white: '#ffffff',
  black_to_white_color: '#ffffff',
  white_to_black_color: '#000000',
  rgbview_color: 'rgba(13, 13, 13, 1)',

};

export const lightColors = {
  primary_color: '#008000',
  tea_green_color: '#cce6cc',
  tea_green_light_color: '#d6f3d6ff',
  secondary_color: '#FE9801',
  secondary_light_color: '#ffcd42ff',
  secondary_light1_color: '#fff2cdff',
  black: '#000000',
  white: '#ffffff',
  white_transparent: '#ffffff7e',
  pine_green_color: '#004D00',
  mint_green_color: '#66BB66',
  earthy_brown_color: '#8B4513',
  gainsboro: "#ebe9e8",
  mint_white: "#F1F8F4",
  mint_dark_white: "#EEF9F0",
  forest_green: "#6baf6b",
  eton_green: "#94cf94",
  bright_gray: "#eaeaea",
  cultured: "#f8f8f8",
  red_light_color: "#fad7d9",
  background_color: '#F4F5F9',
  background_box_color: '#ffffff',
  background_white_color: '#ffffff',
  light_box: '#f9faf9ff',
  bright_gray_dark: '#d9d9d9',
  bright_gray01: '#edededff',
  gray: '#8b8b8b',
  light_gray: "#c1c1c1",
  layer_black: "#00000075",
  light_primary: '#fdf5f6',
  background: '#ffffff',
  light_black: '#535353',
  text_color_white: '#ffffff',
  light_gray_01: '#f6f6f6',
  transparent: 'transparent',
  grey: 'grey',
  red_color: "#e72f07",
  fix_white: '#ffffff',
  black_to_white_color: '#000000ff',
  white_to_black_color: '#ffffffff',
  rgbview_color: 'rgba(0, 0, 0, 0)',

};
